// Generated by struct2jsdoc - https://github.com/uradical/struct2jsdoc

/**
 * @typedef {Object} Order
 * @property {string} id
 * @property {string} orderNumber - Human-readable order number
 * @property {string} customerId - Customer ID
 * @property {string} status - Order status (pending, processing, shipped, delivered)
 * @property {OrderItem[]} items - Order items
 * @property {number} subtotal - Subtotal before tax and shipping
 * @property {number} tax - Tax amount
 * @property {number} shipping - Shipping cost
 * @property {number} total - Total amount
 * @property {string} currency - Currency code
 * @property {Address} shippingAddress - Shipping address
 * @property {Address} [billingAddress] - Billing address (optional, defaults to shipping)
 * @property {string} paymentMethod - Payment method
 * @property {Date} createdAt - Order creation time
 * @property {Date} updatedAt - Last update time
 * @property {Date} [shippedAt] - Shipping time
 * @property {Date} [deliveredAt] - Delivery time
 * @property {string} [notes] - Order notes
 * @property {Discount[]} [discounts] - Applied discounts
 */

/**
 * @typedef {Object} OrderItem
 * @property {string} productId - Product ID
 * @property {string} name - Product name
 * @property {number} quantity - Quantity ordered
 * @property {number} price - Price per unit
 * @property {number} total - Total price (quantity * price)
 * @property {string} [sku] - Stock keeping unit
 */

/**
 * @typedef {Object} Address
 * @property {string} line1 - Address line 1
 * @property {string} [line2] - Address line 2
 * @property {string} city - City
 * @property {string} [state] - State/Province
 * @property {string} postalCode - Postal/ZIP code
 * @property {string} country - Country code (e.g., US, CA, GB)
 */

/**
 * @typedef {Object} Discount
 * @property {string} code - Discount code
 * @property {string} type - Discount type (percentage, fixed)
 * @property {number} amount - Discount amount
 * @property {string} [reason] - Reason for discount
 */

/**
 * @typedef {Object} Statistics
 * @property {number} totalOrders - Total number of orders
 * @property {number} totalRevenue - Total revenue
 * @property {number} averageOrder - Average order value
 * @property {string[]} topProducts - Top selling product IDs
 * @property {Object.<string, number>} revenueByMonth - Revenue grouped by month
 * @property {Object.<string, number>} ordersByStatus - Order counts by status
 */

/**
 * @typedef {Object} APIResponse
 * @property {boolean} success - Whether the request was successful
 * @property {*} [data] - Response data
 * @property {APIError} [error] - Error information if request failed
 * @property {MetaData} [meta] - Additional metadata
 */

/**
 * @typedef {Object} APIError
 * @property {string} code - Error code
 * @property {string} message - Human-readable error message
 * @property {string} [details] - Additional error details
 */

/**
 * @typedef {Object} MetaData
 * @property {number} page - Current page number
 * @property {number} perPage - Items per page
 * @property {number} total - Total number of items
 * @property {number} totalPages - Total number of pages
 */

/**
 * @typedef {Object} Event
 * @property {string} id
 * @property {string} type - Event type
 * @property {Date} timestamp - When the event occurred
 * @property {string} [userId] - User who triggered the event
 * @property {Object.<string, *>} data - Event data
 * @property {string[]} [tags] - Event tags
 */

/**
 * @typedef {Object} PaginatedResponse
 * @property {*[]} items - List of items
 * @property {MetaData} pagination - Pagination information
 */

/**
 * @typedef {Object} Product
 * @property {string} id
 * @property {string} name - Product name
 * @property {string} description - Product description
 * @property {number} price - Product price in USD
 * @property {string} currency - Currency code (e.g., USD, EUR)
 * @property {boolean} inStock - Whether product is in stock
 * @property {string} [sku] - Stock keeping unit
 * @property {string[]} categories - Product categories
 * @property {Image[]} [images] - Product images
 * @property {Variant[]} [variants] - Product variants
 * @property {Dimensions} [dimensions] - Product dimensions
 */

/**
 * @typedef {Object} Image
 * @property {string} url - Image URL
 * @property {string} [alt] - Alternative text
 * @property {number} [width] - Image width in pixels
 * @property {number} [height] - Image height in pixels
 * @property {boolean} [isPrimary] - Whether this is the primary image
 */

/**
 * @typedef {Object} Variant
 * @property {string} id
 * @property {string} name - Variant name
 * @property {string} sku - Variant SKU
 * @property {number} [price] - Variant-specific price
 * @property {Object.<string, string>} attributes - Variant attributes (e.g., color, size)
 */

/**
 * @typedef {Object} Dimensions
 * @property {number} length - Length in inches
 * @property {number} width - Width in inches
 * @property {number} height - Height in inches
 * @property {number} weight - Weight in pounds
 */

/**
 * @typedef {Object} User
 * @property {number} id - Unique user identifier
 * @property {string} username - User's login name
 * @property {string} email - User's email address
 * @property {string} [firstName] - User's first name
 * @property {string} [lastName] - User's last name
 * @property {number} [age] - User's age
 * @property {boolean} isActive - Whether the user account is active
 * @property {Date} createdAt - Account creation timestamp
 * @property {Date} updatedAt - Last update timestamp
 * @property {Profile} [profile] - User's profile information
 * @property {string[]} [tags] - User tags
 */

/**
 * @typedef {Object} Profile
 * @property {string} [bio] - User biography
 * @property {string} [avatarUrl] - URL to user's avatar image
 * @property {string} [website] - User's website
 * @property {string} [location] - User's location
 * @property {Object.<string, string>} [metadata] - Additional metadata
 */

