// Generated by struct2jsdoc - https://github.com/uradical/struct2jsdoc

export interface Order {
  id: string;
  /** Human-readable order number */
  orderNumber: string;
  /** Customer ID */
  customerId: string;
  /** Order status (pending, processing, shipped, delivered) */
  status: string;
  /** Order items */
  items: OrderItem[];
  /** Subtotal before tax and shipping */
  subtotal: number;
  /** Tax amount */
  tax: number;
  /** Shipping cost */
  shipping: number;
  /** Total amount */
  total: number;
  /** Currency code */
  currency: string;
  /** Shipping address */
  shippingAddress: Address;
  /** Billing address (optional, defaults to shipping) */
  billingAddress?: Address;
  /** Payment method */
  paymentMethod: string;
  /** Order creation time */
  createdAt: Date;
  /** Last update time */
  updatedAt: Date;
  /** Shipping time */
  shippedAt?: Date;
  /** Delivery time */
  deliveredAt?: Date;
  /** Order notes */
  notes?: string;
  /** Applied discounts */
  discounts?: Discount[];
}

export interface OrderItem {
  /** Product ID */
  productId: string;
  /** Product name */
  name: string;
  /** Quantity ordered */
  quantity: number;
  /** Price per unit */
  price: number;
  /** Total price (quantity * price) */
  total: number;
  /** Stock keeping unit */
  sku?: string;
}

export interface Address {
  /** Address line 1 */
  line1: string;
  /** Address line 2 */
  line2?: string;
  /** City */
  city: string;
  /** State/Province */
  state?: string;
  /** Postal/ZIP code */
  postalCode: string;
  /** Country code (e.g., US, CA, GB) */
  country: string;
}

export interface Discount {
  /** Discount code */
  code: string;
  /** Discount type (percentage, fixed) */
  type: string;
  /** Discount amount */
  amount: number;
  /** Reason for discount */
  reason?: string;
}

export interface Statistics {
  /** Total number of orders */
  totalOrders: number;
  /** Total revenue */
  totalRevenue: number;
  /** Average order value */
  averageOrder: number;
  /** Top selling product IDs */
  topProducts: string[];
  /** Revenue grouped by month */
  revenueByMonth: Record<string, number>;
  /** Order counts by status */
  ordersByStatus: Record<string, number>;
}

export interface APIResponse {
  /** Whether the request was successful */
  success: boolean;
  /** Response data */
  data?: any;
  /** Error information if request failed */
  error?: APIError;
  /** Additional metadata */
  meta?: MetaData;
}

export interface APIError {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Additional error details */
  details?: string;
}

export interface MetaData {
  /** Current page number */
  page: number;
  /** Items per page */
  perPage: number;
  /** Total number of items */
  total: number;
  /** Total number of pages */
  totalPages: number;
}

export interface Event {
  id: string;
  /** Event type */
  type: string;
  /** When the event occurred */
  timestamp: Date;
  /** User who triggered the event */
  userId?: string;
  /** Event data */
  data: Record<string, any>;
  /** Event tags */
  tags?: string[];
}

export interface PaginatedResponse {
  /** List of items */
  items: any[];
  /** Pagination information */
  pagination: MetaData;
}

export interface Product {
  id: string;
  /** Product name */
  name: string;
  /** Product description */
  description: string;
  /** Product price in USD */
  price: number;
  /** Currency code (e.g., USD, EUR) */
  currency: string;
  /** Whether product is in stock */
  inStock: boolean;
  /** Stock keeping unit */
  sku?: string;
  /** Product categories */
  categories: string[];
  /** Product images */
  images?: Image[];
  /** Product variants */
  variants?: Variant[];
  /** Product dimensions */
  dimensions?: Dimensions;
}

export interface Image {
  /** Image URL */
  url: string;
  /** Alternative text */
  alt?: string;
  /** Image width in pixels */
  width?: number;
  /** Image height in pixels */
  height?: number;
  /** Whether this is the primary image */
  isPrimary?: boolean;
}

export interface Variant {
  id: string;
  /** Variant name */
  name: string;
  /** Variant SKU */
  sku: string;
  /** Variant-specific price */
  price?: number;
  /** Variant attributes (e.g., color, size) */
  attributes: Record<string, string>;
}

export interface Dimensions {
  /** Length in inches */
  length: number;
  /** Width in inches */
  width: number;
  /** Height in inches */
  height: number;
  /** Weight in pounds */
  weight: number;
}

export interface User {
  /** Unique user identifier */
  id: number;
  /** User's login name */
  username: string;
  /** User's email address */
  email: string;
  /** User's first name */
  firstName?: string;
  /** User's last name */
  lastName?: string;
  /** User's age */
  age?: number;
  /** Whether the user account is active */
  isActive: boolean;
  /** Account creation timestamp */
  createdAt: Date;
  /** Last update timestamp */
  updatedAt: Date;
  /** User's profile information */
  profile?: Profile;
  /** User tags */
  tags?: string[];
}

export interface Profile {
  /** User biography */
  bio?: string;
  /** URL to user's avatar image */
  avatarUrl?: string;
  /** User's website */
  website?: string;
  /** User's location */
  location?: string;
  /** Additional metadata */
  metadata?: Record<string, string>;
}

